services:
  db:
    image: pgvector/pgvector:pg16
    container_name: truthlens
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - truthlens_pgdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sahil -d truthlens"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  truthlens_pgdata:
